spring:
  application:
    name: chess-server
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
stockfish:
  path: /usr/bin/stockfish